name: alic-borrowers
static_sites:
  - name: web
    build_command: npm ci && npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html
    github:
      repo: latsonml/alic-borrowers
      branch: main
      deploy_on_push: true
